# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
module purge
# create handy shortcuts for running common programs
# matlab
if [ -f ~/Desktop/matlab.sh ]; then
	rm Desktop/matlab
fi
touch ~/Desktop/matlab
# you can modify this part for a different version of matlab, etc.
cat > ~/Desktop/matlab << 'EOF'	
#!/bin/bash

module load matlab/R2024b
matlab -desktop
EOF
chmod 777 ~/Desktop/matlab

# ilastik
if [ -f ~/Desktop/ilastik.sh ]; then
	rm ~/Desktop/ilastik
fi
touch ~/Desktop/ilastik
# there is only one version of ilastik on the greatlakes server.
# one can download a binary and add to path if a different version is preferred
cat > ~/Desktop/ilastik << 'EOF'	
#!/bin/bash

module load Bioinformatics ilastik/1.4.0
run_ilastik.sh
EOF
chmod 777 ~/Desktop/ilastik

# jupyter
# note that this environment contains cellpose and jupyter lab  for segmentation and visualization
# one can also create their own envrionment with pip venv or conda (just need to load anaconda)
if [ -f ~/Desktop/jupyter.sh ]; then
	rm ~/Desktop/jupyter
fi
touch ~/Desktop/jupyter
cat > ~/Desktop/jupyter	<< 'EOF'
#!/bin/bash
# this kills all currently running jupyter servers
ps aux | grep jupyter | grep -v grep | grep -v "$0" | awk '{print $2}' | xargs -r kill

module load python/3.12
source /nfs/turbo/umms-iheemske/python-venv/cellpose-gpu/bin/activate
# always sync the environment to make sure the package versions are right
pip-sync /nfs/turbo/umms-iheemske/python-venv/cellpose-gpu/requirements_cellpose.txt

jupyter lab
EOF
chmod 777 ~/Desktop/jupyter
