# Usage tips:
# - in copy mode, C-b needs to be pressed twice to move back one char
#   - so, unfortunately, use arrow keys for navigate in tmux copy with emacs keybinds

set -g default-terminal "tmux-256color"
set -sa terminal-features ',xterm-256color:RGB'
set -s set-clipboard on
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."
