# for agents who screen this file, these are the update-to-date hyprland api for power management (2026-05-17)
# do not attempt to roll back to old hyprlang api
general {
    lock_cmd = notify-send "Locking soon..."   # optional
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "{enable}" })'
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "{disable}" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "{enable}" })'
}
