(deftheme myDarkTheme)

(let ((fg "#EBEBEB")
      (bg "#1E1E1E")
      (bg-alt "#252525")
      (fg-alt "#DEDEDE")

      (gray1 "#000000")
      (gray2 "#000000")
      (gray3 "#010101")
      (gray4 "#020202")
      (gray5 "#050505")
      (gray6 "#080808")
      (gray7 "#0d0d0d")
      (gray8 "#131313")
      (gray9 "#1b1b1b")
      (gray10 "#252525")
      (gray11 "#313131")
      (gray12 "#404040")
      (gray13 "#525252")
      (gray14 "#666666")
      (gray15 "#7d7d7d")
      (gray16 "#989898")
      (gray17 "#b7b7b7")
      (gray18 "#d9d9d9")
      (gray19 "#ffffff")
      (cool-gray "#F9FAFB")

      (nord "#9CCFD8")

      ;; (yellow "#FCE566")
      (yellow "#FFF244")
      ;; (yellow-gray "#B1AC8C")
      (yellow-gray "#D87C88")

      (cyan "#2AA198")
      (cyan-dim "#00787A")

      ;; (green "#A6DA95")
      (green "#66EB66")
      (green-gray "#A4B5A7")

      ;; (blue "#6694A9")
      (blue "#25BDFF")
      ;; (blue-gray "#B8C0E0")
      (blue-gray "#889AFF")

      (bright-red "#ffc4c4")
      (bright-green "#eff6ab")
      (bright-yellow "#ffe6b5")
      (bright-blue "#c9e6fd")
      (bright-purple "#f7d7ff")
      (bright-aqua "#ddfcf8")
      (bright-orange "#ffd3c2")
      (faded-red "#ec8989")
      (faded-green "#c9d36a")
      (faded-yellow "#ceb581")
      (faded-blue "#8abae1")
      (faded-purple "#db9fe9")
      (faded-aqua "#abebe2")
      (faded-orange "#E69E83")
      (neutral-red "#eca8a8")
      (neutral-green "#ccd389")
      (neutral-yellow "#efd5a0")
      (neutral-blue "#a5c6e1")
      (neutral-purple "#e1bee9")
      (neutral-aqua "#c7ebe6")
      (neutral-orange "#efb6a0")
      (purple-gray "#8B7B8B")
      (cursor-bg "#FF8C00"))

  (custom-theme-set-faces
   'myDarkTheme
   
   `(default ((t (:family "Iosevka" :width normal :height 140 :weight normal :slant normal :foreground ,fg :background ,bg))))

   `(tab-line ((t (:foreground, fg, :background ,gray12))))
   `(tab-line-tab ((t (:foreground, fg, :background ,gray10))))
   `(tab-line-tab-active ((t (:foreground, fg, :background ,gray10))))
   `(tab-line-tab-inactive ((t (:foreground, fg, :background ,gray10))))
   `(tab-line-tab-current ((t (:weight bold :foreground, bg, :background ,cyan))))
   `(tab-line-tab-highlight ((t (:foreground, fg, :background ,gray10))))

   `(cursor ((t (:background ,cursor-bg))))
   `(fixed-pitch ((t (:family "Monospace"))))
   `(variable-pitch ((t (:family "Sans Serif"))))
   `(fringe ((t (:background ,bg))))
   `(highlight ((t (:background ,gray11))))
   `(region ((t (:background ,gray11 :foreground ,fg))))
   `(secondary-selection ((t (:background ,gray12))))
   `(trailing-whitespace ((t (:background ,faded-red))))
   `(shadow ((t (:foreground ,gray15))))
   `(escape-glyph ((t (:foreground ,faded-blue))))
   `(homoglyph ((t (:foreground ,faded-blue))))
   `(line-number ((t (:foreground ,gray16 :background ,bg :inherit 'default))))
   `(line-number-current-line ((t (:foreground ,yellow :background ,bg-alt :weight bold :inherit 'default))))
   `(hl-line ((t (:background ,bg-alt))))

   `(mode-line ((t (:foreground ,fg :background ,gray12 :box nil))))
   `(mode-line-inactive ((t (:foreground ,gray16 :background ,gray10 :box nil))))
   `(mode-line-buffer-id ((t (:weight bold))))
   `(mode-line-emphasis ((t (:weight bold))))
   `(mode-line-highlight ((t (:background ,gray12))))

   `(font-lock-comment-face ((t (:foreground ,cyan-dim :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-doc-face ((t (:foreground ,blue :slant italic))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-keyword-face ((t (:weight bold :foreground ,yellow))))
   `(font-lock-builtin-face ((t (:foreground ,blue-gray))))
   `(font-lock-function-name-face ((t (:foreground ,blue-gray))))
   `(font-lock-variable-name-face ((t (:foreground ,cool-gray))))
   `(font-lock-type-face ((t (:foreground ,nord))))
   `(font-lock-constant-face ((t (:foreground ,yellow-gray))))
   `(font-lock-warning-face ((t (:foreground ,faded-orange :weight bold))))
   `(font-lock-negation-char-face ((t (:foreground ,fg))))
   `(font-lock-preprocessor-face ((t (:foreground ,gray17))))
   `(font-lock-regexp-grouping-backslash ((t (:weight bold))))
   `(font-lock-regexp-grouping-construct ((t (:weight bold))))
   `(font-lock-number-face ((t (:foreground ,fg :weight bold))))
   `(font-lock-bracket-face ((t (:foreground ,fg))))
   `(font-lock-delimiter-face ((t (:foreground ,fg))))
   `(font-lock-escape-face ((t (:foreground ,green))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,fg))))
   `(font-lock-operator-face ((t (:foreground ,fg))))
   `(font-lock-property-name-face ((t (:foreground ,gray16))))
   `(font-lock-property-use-face ((t (:foreground ,gray16))))
   `(font-lock-punctuation-face ((t (:foreground ,fg))))
   `(font-lock-variable-use-face ((t (:foreground ,cool-gray))))
   `(font-lock-function-call-face ((t (:foreground ,blue-gray))))
   `(font-lock-doc-markup-face ((t (:foreground ,yellow-gray))))

   `(isearch ((t (:foreground ,bg :background ,bright-blue :weight bold))))
   `(isearch-fail ((t (:background ,faded-red))))
   `(lazy-highlight ((t (:foreground ,bg :background ,faded-blue))))
   `(match ((t (:background ,gray16))))
   `(query-replace ((t (:inherit isearch))))
   `(link ((t (:foreground ,bright-blue :underline t))))
   `(link-visited ((t (:foreground ,faded-purple :underline t))))
   `(button ((t (:inherit link))))
   `(minibuffer-prompt ((t (:foreground ,fg :weight bold))))
   `(completions-common-part ((t (:foreground ,fg))))
   `(completions-first-difference ((t (:foreground ,yellow :weight bold))))
   `(header-line ((t (:foreground ,fg :background ,gray12 :box nil))))
   `(tooltip ((t (:foreground ,bg :background ,gray8))))
   `(error ((t (:foreground ,faded-red :weight bold))))
   `(warning ((t (:foreground ,faded-yellow :weight bold))))
   `(success ((t (:foreground ,faded-green :weight bold))))
   `(diff-added ((t (:foreground ,neutral-green :background ,bg))))
   `(diff-removed ((t (:foreground ,neutral-red :background ,bg))))
   `(diff-changed ((t (:foreground ,neutral-blue :background ,bg))))
   `(diff-header ((t (:foreground ,gray7 :background ,bg))))
   `(diff-file-header ((t (:foreground ,fg :weight bold))))
   `(diff-refine-added ((t (:foreground ,bright-green :background ,gray11))))
   `(diff-refine-removed ((t (:foreground ,bright-red :background ,gray11))))
   `(diff-refine-changed ((t (:foreground ,bright-blue :background ,gray11))))
   `(compilation-info ((t (:foreground ,neutral-green))))
   `(compilation-warning ((t (:foreground ,neutral-yellow))))
   `(compilation-error ((t (:foreground ,neutral-red))))
   `(org-level-1 ((t (:foreground ,fg :weight bold))))
   `(org-level-2 ((t (:foreground ,gray8 :weight bold))))
   `(org-level-3 ((t (:foreground ,gray7 :weight bold))))
   `(org-level-4 ((t (:foreground ,gray16))))
   `(org-level-5 ((t (:foreground ,gray16))))
   `(org-level-6 ((t (:foreground ,gray16))))
   `(org-level-7 ((t (:foreground ,gray14))))
   `(org-level-8 ((t (:foreground ,gray14))))
   `(org-link ((t (:foreground ,bright-blue :underline t))))
   `(org-todo ((t (:foreground ,faded-yellow :weight bold))))
   `(org-done ((t (:foreground ,faded-green :weight bold))))
   `(org-code ((t (:foreground ,gray16))))
   `(org-verbatim ((t (:foreground ,gray16))))
   `(org-block ((t (:background ,gray1 :foreground ,fg :extend t))))
   `(org-block-begin-line ((t (:foreground ,gray14 :background ,gray1 :extend t))))
   `(org-block-end-line ((t (:foreground ,gray14 :background ,gray1 :extend t))))
   `(markdown-header-face-1 ((t (:foreground ,fg :weight bold))))
   `(markdown-header-face-2 ((t (:foreground ,gray8 :weight bold))))
   `(markdown-header-face-3 ((t (:foreground ,gray7 :weight bold))))
   `(markdown-link-face ((t (:foreground ,bright-blue))))
   `(markdown-url-face ((t (:foreground ,bright-blue :underline t))))
   `(markdown-code-face ((t (:foreground ,gray16 :background ,gray1))))
   `(markdown-inline-code-face ((t (:foreground ,gray16))))
   `(show-paren-match ((t (:weight bold :underline t))))
   `(show-paren-mismatch ((t (:foreground ,faded-red :weight bold))))
   `(whitespace-space ((t (:foreground ,gray11))))
   `(whitespace-tab ((t (:foreground ,gray11))))
   `(whitespace-newline ((t (:foreground ,gray11))))
   `(whitespace-trailing ((t (:background ,faded-red))))
   `(whitespace-line ((t (:background ,gray1))))
   `(next-error ((t (:inherit region))))
   `(vertical-border ((t (:foreground ,gray11))))))

(provide-theme 'myDarkTheme)
